import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {AuthProvider} from "@/hooks/useAuth";

import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { Toaster } from "react-hot-toast";
import NotificationProvider from '@/components/notifications/NotificationProvider';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <AuthProvider>
          <NotificationProvider>
          <Header />
          {children}
          <Toaster position="top-right" />
          <Footer />
          </NotificationProvider>
      </AuthProvider>
      </body>
    </html>

  );
}
